// SPDX-License-Identifier: MIT OR Apache-2.0

//! Heap snapshot infra ceilings (re-export named constants).

pub use crate::constants::{
    HEAP_DEFAULT_MAX_CLASS_NODES as DEFAULT_MAX_CLASS_NODES,
    HEAP_DEFAULT_MAX_EDGES as DEFAULT_MAX_EDGES, HEAP_DEFAULT_MAX_PATHS as DEFAULT_MAX_PATHS,
    HEAP_DEFAULT_MAX_PATH_DEPTH as DEFAULT_MAX_PATH_DEPTH,
    HEAP_DEFAULT_MAX_RETAINERS as DEFAULT_MAX_RETAINERS, HEAP_DOMINATOR_MAX_STATES as MAX_STATES,
    HEAP_SNAPSHOT_MAX_BYTES as MAX_HEAP_SNAPSHOT_BYTES,
};
