//! Permanent gate: every subcommand carries a help description (GAP-017).
//!
//! # Why this file exists
//!
//! `tests/clap_arg_coverage.rs` already asserts that every TOP-LEVEL subcommand
//! renders help without erroring. That check stays green when the description is
//! missing, because clap renders a usage block regardless — and it never
//! descends, so the nested families are invisible to it. The families named in
//! the gap are exactly the nested ones: `perf`, `heap`, `extension`, `console`,
//! `assert`, `net`, `screencast`, `devtools3p`, `webmcp` and `dialog`.
//!
//! Renderability is not description. This gate walks the whole tree and requires
//! `about` to be present and non-empty at every depth.
//!
//! # Why the detector is a function
//!
//! The live case and the synthetic case call the SAME `subcommands_without_about`.
//! A detector exercised only against the real tree proves nothing about its own
//! sensitivity: if it walked no deeper than the first level, or if it treated a
//! blank string as a description, the live case would still be green. The
//! synthetic case is what closes that, and it is the reason the walk is not
//! inlined into the test that uses it.
//!
//! # The three committed cases
//!
//! | case | what it proves |
//! |---|---|
//! | positive control | the real tree has a description at every depth |
//! | negative, synthetic | the detector finds a missing description nested two levels down |
//! | declared exclusion | clap's own generated `help` is the only accepted omission |
//!
//! # What this file does NOT cover
//!
//! - It says nothing about the QUALITY of a description; a string that merely
//!   repeats the subcommand name passes here. That is a review concern, not one
//!   a gate can decide.
//! - It does not cover argument-level help, only subcommands.
//! - It does not cover the `commands` inventory or the emitted `schema`; those
//!   are separate surfaces with their own gates.
//! - It needs no browser, so it never skips.

use clap::{Arg, Command, CommandFactory};

use browser_automation_cli::cli::Cli;

/// Subcommands generated by clap itself rather than declared in this codebase.
///
/// `help` is synthesized by clap and its text is clap's, not ours, so requiring
/// an `about` on it would be requiring a change we cannot make in `src/cli/`.
/// This list is deliberately short: an entry here is an admission that one
/// subcommand is undiscoverable from `--help`, and it needs a reason that is
/// about the tool and not about the effort of writing the sentence.
const GENERATED_SUBCOMMANDS: &[&str] = &["help"];

/// Every subcommand, at any depth, whose `about` is absent or blank.
///
/// Returns dotted paths (`heap.summary`) so a failure names the exact node
/// instead of a bare leaf name that may repeat across families.
fn subcommands_without_about(root: &Command) -> Vec<String> {
    fn walk(cmd: &Command, prefix: &str, out: &mut Vec<String>) {
        for sub in cmd.get_subcommands() {
            let name = sub.get_name();
            if GENERATED_SUBCOMMANDS.contains(&name) {
                continue;
            }
            let path = if prefix.is_empty() {
                name.to_string()
            } else {
                format!("{prefix}.{name}")
            };
            // A blank string is not a description. Checking only for `None`
            // would let `#[doc = " "]` through.
            let described = sub
                .get_about()
                .map(|a| !a.to_string().trim().is_empty())
                .unwrap_or(false);
            if !described {
                out.push(path.clone());
            }
            walk(sub, &path, out);
        }
    }
    let mut out = Vec::new();
    walk(root, "", &mut out);
    out
}

/// POSITIVE CONTROL: the real command tree is fully described.
///
/// The gap counted thirty-six omissions concentrated in the nested families, so
/// the failure message groups by family: a regression that adds one variant to
/// `heap` should read as `heap.<name>`, not as an anonymous count.
#[test]
fn every_subcommand_at_every_depth_has_a_description() {
    let missing =
        browser_automation_cli::cli::on_clap_stack(|| subcommands_without_about(&Cli::command()));
    assert!(
        missing.is_empty(),
        "{} subcommand(s) have no help description: {}. \
         Add a doc comment to the matching variant in src/cli/; in clap derive a \
         `///` on a variant becomes its `about`, so this is user-visible surface \
         and not internal documentation.",
        missing.len(),
        missing.join(", ")
    );
}

/// NEGATIVE, SYNTHETIC: the detector finds an omission nested two levels down.
///
/// This is the case that gives the positive control its meaning. Three shapes
/// are planted at once, because each corresponds to a different way the walk
/// could be wrong: a missing `about` at depth two catches a walk that does not
/// recurse, a blank `about` catches a presence-only check, and a described
/// sibling catches a detector that simply reports everything it visits.
#[test]
fn the_detector_finds_a_missing_description_nested_two_levels_down() {
    let tree = Command::new("probe")
        .subcommand(
            Command::new("described")
                .about("has a description")
                .subcommand(Command::new("deep-missing"))
                .subcommand(Command::new("deep-blank").about("   "))
                .subcommand(Command::new("deep-ok").about("also described")),
        )
        .subcommand(Command::new("shallow-missing").arg(Arg::new("x")));

    let missing = subcommands_without_about(&tree);

    assert!(
        missing.contains(&"described.deep-missing".to_string()),
        "a subcommand with no about at depth two must be reported; got {missing:?}. \
         An empty result here means the walk stops at the first level, which is \
         exactly the blind spot this gate was written to remove."
    );
    assert!(
        missing.contains(&"described.deep-blank".to_string()),
        "a blank about is not a description and must be reported; got {missing:?}"
    );
    assert!(
        missing.contains(&"shallow-missing".to_string()),
        "a top-level omission must be reported too; got {missing:?}"
    );
    assert!(
        !missing.contains(&"described".to_string()),
        "a described subcommand must NOT be reported; got {missing:?}. \
         A detector that flags everything would pass the assertions above and \
         still be worthless."
    );
    assert!(
        !missing.contains(&"described.deep-ok".to_string()),
        "a described leaf must NOT be reported; got {missing:?}"
    );
}

/// DECLARED EXCLUSION: clap's generated `help` is skipped, and nothing else is.
///
/// The exclusion is what makes the positive control honest, so it has to be
/// verifiable rather than asserted in prose. Both halves matter: that the list
/// is actually applied, and that it has not quietly grown into a place to hide
/// omissions.
#[test]
fn the_only_declared_exclusion_is_claps_own_generated_help() {
    assert_eq!(
        GENERATED_SUBCOMMANDS,
        &["help"],
        "the exclusion list grew. Every entry is one subcommand a caller cannot \
         discover from --help, so an addition needs a written reason in the \
         constant's doc comment."
    );

    // The list is applied, not decorative: an undescribed `help` is skipped
    // while its equally undescribed sibling is reported.
    let tree = Command::new("probe")
        .subcommand(Command::new("help"))
        .subcommand(Command::new("not-help"));
    let missing = subcommands_without_about(&tree);
    assert_eq!(
        missing,
        vec!["not-help".to_string()],
        "the exclusion must cover `help` and only `help`; got {missing:?}"
    );
}
