// SPDX-License-Identifier: MIT OR Apache-2.0
//! CDP Input domain types.
use serde::Serialize;

/// Mirrors CDP `Input.dispatchMouseEvent` request.
///
/// Dispatches a mouse event to the page.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchMouseEventParams {
    /// Event kind: `mousePressed`, `mouseReleased`, `mouseMoved` or `mouseWheel`.
    ///
    /// Renamed because `type` is a Rust keyword; the wire name stays `type`.
    #[serde(rename = "type")]
    pub event_type: String,
    /// X coordinate of the event relative to the main frame's viewport in CSS pixels.
    pub x: f64,
    /// Y coordinate of the event relative to the main frame's viewport in CSS pixels.
    pub y: f64,
    /// Mouse button (default: "none").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button: Option<String>,
    /// A number indicating which buttons are pressed on the mouse when a mouse event is
    /// triggered. Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub buttons: Option<i32>,
    /// Number of times the mouse button was clicked (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i32>,
    /// X delta in CSS pixels for mouse wheel event (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta_x: Option<f64>,
    /// Y delta in CSS pixels for mouse wheel event (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta_y: Option<f64>,
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<i32>,
}

/// Mirrors CDP `Input.dispatchKeyEvent` request.
///
/// Dispatches a key event to the page.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchKeyEventParams {
    /// Event kind: `keyDown`, `keyUp`, `rawKeyDown` or `char`.
    ///
    /// Renamed because `type` is a Rust keyword; the wire name stays `type`.
    #[serde(rename = "type")]
    pub event_type: String,
    /// Unique DOM defined string value describing the meaning of the key in the context of
    /// active modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Text as generated by processing a virtual key code with a keyboard layout. Not needed
    /// for for `keyUp` and `rawKeyDown` events (default: "")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Text that would have been generated by the keyboard if no modifiers were pressed (except
    /// for shift). Useful for shortcut (accelerator) key handling (default: "").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unmodified_text: Option<String>,
    /// Windows virtual key code (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub windows_virtual_key_code: Option<i32>,
    /// Native virtual key code (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_virtual_key_code: Option<i32>,
    /// Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
    /// (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<i32>,
}

/// Mirrors CDP `Input.insertText` request.
///
/// This method emulates inserting text that doesn't come from a key press, for example an emoji
/// keyboard or an IME.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InsertTextParams {
    /// Text to insert verbatim, without synthesising key events for it.
    pub text: String,
}

// ---------------------------------------------------------------------------
// Page.captureScreenshot
// ---------------------------------------------------------------------------
